sudo: false

language: node_js

node_js:
  - iojs
  - 0.10
  - 0.12
  - 4
  - 5
  - 6

matrix:
  include:
    - node_js: stable
      env: SENDCOVERAGE=1 RUNLINT=1

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install
  - npm install -g codecov
  - npm install -g bithound

script:
  - if [ $RUNLINT ]; then npm run lint; fi
  - npm run coverage
  - bithound check git@github.com:maxkoryukov/mkdirp-bluebird.git

after_success:
  # - if [ $SENDCOVERAGE ]; then codecov; fi
  - codecov
